// webapps/connect2ic-vue/src/App.vue
<script setup lang="ts">
import logo from "./assets/dfinity.svg"
/*
 * Connect2ic provides essential utilities for IC app development
 */
import { reactive } from "vue"
import { createClient } from "@connect2ic/core"
import { defaultProviders } from "@connect2ic/core/providers"
import {
  ConnectButton,
  useConnect,
  useWallet,
  ConnectDialog,
  Connect2ICProvider,
} from "@connect2ic/vue"
import { tokenOptions, NFTOptions } from './utils/'

import  {idlFactory as exampleIdl} from './candid/example.idl'
import type { _SERVICE as exampleService } from "./candid/example"

import "@connect2ic/core/style.css"
const { isConnected, connect, activeProvider, principal } = useConnect()
const [walletProvider] = useWallet()
const data = reactive({
  loading: false,
  balance: "0.0",
  newActor: null,
})

const queryBalance = async () => {
  data.loading = true
  const result = await walletProvider.queryBalance()
  console.log("queryBalance", JSON.stringify(result))
  data.balance = (result as any).value[0].amount
  data.loading = false
}

const createActor = async (values: { canisterId: string }) => {
  data.loading = true
  // @ts-ignore
  const { value: actor } = await activeProvider.createActor<exampleService>(
    values.canisterId,
    exampleIdl,
  )
  data.newActor = actor
  console.log("actor", actor)
  const result1 = await actor.created_apps()
  console.log("result1", result1)
  data.loading = false
}

// const handleConnect = async () => {
//   console.log('connect')
//   const result = connect((window as any).icx ? 'icx' : 'astrox');
//   console.log('result', result)
// }

const transferToken = async (values: { [key: string]: string }) => {
  data.loading = true
  const reuslt = await walletProvider.requestTransfer({
    to: values.to,
    standard: values.standard,
    symbol: values.symbol,
    amount: Number(values.amount),
  })
  console.log("transfer    end", reuslt)
  data.loading = false
}

const transferNFT = async (values: { [key: string]: string }) => {
  data.loading = true
  const reuslt = await walletProvider.requestTransferNFT({
    to: values.to,
    standard: values.standard,
    canisterId: values.canisterId,
    tokenIdentifier: values.tokenIdentifier,
    tokenIndex: Number(values.tokenIndex),
  })
  data.loading = false
}

const client = createClient({
  providers: defaultProviders,
  globalProviderConfig: {},
})
</script>

<template>
  <Connect2ICProvider :client="client">
    <div class="App">
      <div class="auth-section">
        <ConnectButton />
      </div>
      <ConnectDialog />
      <header class="App-header">
        <img :src="logo" class="App-logo" alt="logo" />
        <p class="slogan">Connect2ic Vue example</p>
      </header>
      <a-space size="middle" direction="vertical">
        <a-row :v-if="isConnected" :gutter="{ sm: 10, md: 24 }">
          <a-col :xs="24" :md="12">
            <a-button
              type="primary"
              :loading="data.loading"
              :onClick="queryBalance"
              >queryBalance</a-button
            >
            <p :style="{ marginTop: 10 }">Balance: {{ data.balance }}</p>
          </a-col>
          <a-col :xs="24" md="12">
            <a-form :onFinish="createActor">
              <a-form-item name="canisterId">
                <Input placeholder="canisterId" />
              </a-form-item>
              <a-button type="primary" :loading="data.loading" htmlType="submit"
                >createActor</a-button
              >
            </a-form>
          </a-col>
        </a-row>
        <div :v-if="isConnected">
          <h2>Transaction example</h2>
          <a-row :gutter="{ sm: 10, md: 24 }">
                <a-col :xs="24" :md="12">
                  <a-form
                    :initialValues="{
                      standard: 'ICP',
                      symbol: 'ICP'
                    }"
                    :onFinish="transferToken">
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="amount"
                      label="Amount"

                    >
                      <Input placeholder='Amount' />
                    </a-form-item>

                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="to"
                      label="To"
                    >
                      <Input placeholder='To' />
                    </a-form-item>
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="standard"
                      label="Standard"
                    >
                      <Select
                        :style="{ maxWidth: 120 }"
                        :options="tokenOptions"
                        placeholder="Standard"
                      >
                      </Select>
                    </a-form-item>
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="symbol"
                      label="Symbol"
                    >
                      <Select
                        :style="{ maxWidth: 120 }"
                        options={tokenOptions}
                        placeholder="Symbol"
                      >
                      </Select>
                    </a-form-item>
                    <div :style="{ textAlign: 'right' }">
                      <a-button type="primary" loading={loading} htmlType="submit" >Transfer Token</a-button>
                    </div>
                  </a-form>
                </a-col>
                <a-col xs={24} md={12}>
                  <a-form
                    onFinish={transferNFT}
                    :initialValues="{
                      standard: 'EXT',
                    }"
                  >
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="tokenIdentifier"
                      label="TokenIdentifier"
                    >
                      <Input placeholder='TokenIdentifier' />
                    </a-form-item>
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="tokenIndex"
                      label="TokenIndex"
                    >
                      <Input placeholder='TokenIndex' />
                    </a-form-item>
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="canisterId"
                      label="CanisterId"
                    >
                      <Input placeholder='CanisterId' />
                    </a-form-item>
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="to"
                      label="To"
                    >
                      <Input placeholder='To' />
                    </a-form-item>
                    <a-form-item
                      :labelCol="{ span: 6 }"
                      name="standard"
                      label="Standard"
                    >
                      <Select
                        :style="{ maxWidth: 120 }"
                        :options="NFTOptions"
                        placeholder="Standard"
                      >
                      </Select>
                    </a-form-item>
                    <div :style="{ textAlign: 'right' }">
                      <a-button type="primary" loading={loading} htmlType="submit" >Transfer NFT</a-button>
                    </div>
                  </a-form>
                </a-col>
              </a-row>
        </div>
      </a-space>
    </div>
  </Connect2ICProvider>
</template>

<style>
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  color: #424242;
}

button {
  font-weight: 600;
}

.slogan {
  font-size: 1.7em;
  margin-bottom: 0;
}

.twitter {
  font-size: 0.4em;
}

.App-logo {
  height: 14vmin;
  pointer-events: none;
  transform: scale(1);
  animation: pulse 3s infinite;
}

.App-header {
  height: calc(100vh - 70px);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
}

.examples {
  padding: 30px 100px;
  display: grid;
  grid-gap: 30px;
  grid-template-columns: 1fr 1fr 1fr;
}

.examples-title {
  font-size: 1.3em;
  margin-bottom: 0;
  text-align: center;
}

.example {
  padding: 50px 50px;
  min-height: 300px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  /*border: 1px solid black;*/
  /*background: #f4f4f4;*/
  border-radius: 15px;
}

.example-disabled {
  font-size: 1.3em;
  color: #9e9e9e;
}

.demo-button {
  background: #a02480;
  padding: 0 1.3em;
  margin-top: 1em;
  border-radius: 60px;
  font-size: 0.7em;
  height: 35px;
  outline: 0;
  border: 0;
  cursor: pointer;
  color: white;
}

.demo-button:active {
  color: white;
  background: #979799;
}

.auth-section {
  padding: 1em;
  display: flex;
  justify-content: flex-end;
  align-items: center;
  text-align: right;
  position: fixed;
  top: 0;
  right: 0;
}

@keyframes pulse {
  0% {
    transform: scale(0.97);
    opacity: 0;
  }

  70% {
    transform: scale(1);
    opacity: 1;
  }

  100% {
    transform: scale(0.97);
    opacity: 0;
  }
}
</style>

// webapps/connect2ic-react/src/App.tsx
import React, { ChangeEvent, useEffect, useState } from "react"
import logo from "./assets/dfinity.svg"
// import VConsole from 'vconsole';
/*
 * Import canister definitions like this:
 */
import { Button, Divider, Form, Input, Select, Space, Col, Descriptions, Row } from "antd"

import {
  useConnect,
  useTransfer,
  ConnectButton,
  Connect2ICProvider,
  useBalance,
  useWallet,
  ConnectDialog,
  useClient,
} from "@connect2ic/react"
import { balanceFromString, balanceToString } from "./utils/converters"
import { randomBytes } from "./utils/random"
import { fromHexString } from "@dfinity/candid"

import { Principal } from "@dfinity/principal"
import { CreateActorResult, createClient } from "@connect2ic/core"
import {
  AstroX,
  ICX,
  defaultProviders,
  PlugWallet,
  InfinityWallet,
  NFID,
  StoicWallet,
  InternetIdentity,
  walletProviders,
} from "@connect2ic/core/providers"
/*
 * Import connect2ic  css
 */
import "@connect2ic/core/style.css"
import 'antd/dist/antd.css'
import { NFTOptions, tokenOptions } from "./utils"
import  {idlFactory as exampleIdl} from './candid/example.idl'
import { _SERVICE as exampleService } from "./candid/example"
import { ActorSubclass } from "@dfinity/agent"
// const ConnectButton = ({
//   onClick,
//   text,
// }: {
//   onClick: () => Promise<void>
//   text: string
// }) => {
//   return (
//     <>
//       <Button onClick={onClick}>{text}</Button>
//     </>
//   )
// }
// const vConsole = new VConsole();

function App() {
  const { isConnected, activeProvider, principal } = useConnect()
  const client = useClient()
  const { connect } = useConnect()
  const [walletProvider] = useWallet()
  const [balance, setBalance] = useState<boolean | string>(false)
  const [loading, setLoading] = useState(false)
  const [newActor, setNewActor] = useState<ActorSubclass<exampleService>>()

  useEffect(() => {
    if (isConnected) {
      console.log('walletProvider', walletProvider)
      console.log('activeProvider', activeProvider)
    }
  }, [isConnected])

  const queryBalance = async () => {
    setLoading(true)
    const result = await walletProvider.queryBalance()
    console.log('queryBalance', JSON.stringify(result))
    setBalance((result as any).value[0].amount)
    setLoading(false)
  }

  const createActor = async (values: { canisterId: string }) => {
    setLoading(true)
    // @ts-ignore
    const {value: actor} = await activeProvider.createActor<exampleService>(values.canisterId, exampleIdl)
    setNewActor(actor)
    console.log('actor', actor)
    const result1 = await actor.created_apps()
    console.log('result1', result1)
    setLoading(false)
  }

  // const handleConnect = async () => {
  //   console.log('connect')
  //   const result = connect((window as any).icx ? 'icx' : 'astrox');
  //   console.log('result', result)
  // }

  const transferToken = async (values: {
    [key: string]: string
  }) => {
    try {
      setLoading(true)
      const reuslt = await walletProvider.requestTransfer({
        to: values.to,
        standard: values.standard,
        symbol: values.symbol,
        amount: Number(values.amount),
        memo: BigInt(values.memo),
      })
      console.log('transfer    end', reuslt)
      setLoading(false)
    } catch (err){
      setLoading(false)
    }
    
  }

  const transferNFT = async (values: {
    [key: string]: string
  }) => {
    try {
      setLoading(true)
      const reuslt = await walletProvider.requestTransferNFT({
        to: values.to,
        standard: values.standard,
        canisterId: values.canisterId,
        tokenIdentifier: values.tokenIdentifier,
        tokenIndex: Number(values.tokenIndex),
        memo: BigInt(values.memo),
      })
      setLoading(false)
    } catch(err) {
      setLoading(false)
    }
   
  }

  return (
    <div className="container">
      <div className="auth-section">
        <ConnectButton />
      </div>
      <ConnectDialog />
      <h1 style={{ textAlign: "center", marginBottom: 30 }}>
        Connect2ic Example
      </h1>
      <Space size="middle" direction="vertical">
        {
          isConnected ? (
            <Row gutter={{ sm: 10, md: 24 }}>
              <Col xs={24} md={12}>
                <Button type="primary" loading={loading} onClick={queryBalance}>queryBalance</Button>
                {
                  balance !== undefined ?
                    <p style={{ marginTop: 10 }}>Balance: {balance}</p> : null
                }
              </Col>
              <Col xs={24} md={12}>
                <Form onFinish={createActor}>
                  <Form.Item name="canisterId">
                    <Input placeholder='canisterId' />
                  </Form.Item>
                  <Button type="primary" loading={loading} htmlType="submit">createActor</Button>
                </Form>
              </Col>
            </Row>
          ) : null
        }
        {
          isConnected ? (
            <>
              <h2>Transaction example</h2>
              <Row gutter={{ sm: 10, md: 24 }}>
                <Col xs={24} md={12}>
                  <Form
                    initialValues={{
                      standard: 'ICP',
                      symbol: 'ICP'
                    }}
                    onFinish={transferToken}>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="amount"
                      label="Amount"

                    >
                      <Input placeholder='Amount' />
                    </Form.Item>

                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="to"
                      label="To"
                    >
                      <Input placeholder='To' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="memo"
                      label="Memo"
                    >
                      <Input placeholder='Memo' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="standard"
                      label="Standard"
                    >
                      <Select
                        style={{ maxWidth: 120 }}
                        options={tokenOptions}
                        placeholder="Standard"
                      >
                      </Select>
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="symbol"
                      label="Symbol"
                    >
                      <Select
                        style={{ maxWidth: 120 }}
                        options={tokenOptions}
                        placeholder="Symbol"
                      >
                      </Select>
                    </Form.Item>
                    <div style={{ textAlign: 'right' }}>
                      <Button type="primary" loading={loading} htmlType="submit" >Transfer Token</Button>
                    </div>
                  </Form>
                </Col>
                <Col xs={24} md={12}>
                  <Form
                    onFinish={transferNFT}
                    initialValues={{
                      standard: 'EXT',
                    }}
                  >
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="tokenIdentifier"
                      label="TokenIdentifier"
                    >
                      <Input placeholder='TokenIdentifier' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="tokenIndex"
                      label="TokenIndex"
                    >
                      <Input placeholder='TokenIndex' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="canisterId"
                      label="CanisterId"
                    >
                      <Input placeholder='CanisterId' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="to"
                      label="To"
                    >
                      <Input placeholder='To' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="memo"
                      label="Memo"
                    >
                      <Input placeholder='Memo' />
                    </Form.Item>
                    <Form.Item
                      labelCol={{ span: 6 }}
                      name="standard"
                      label="Standard"
                    >
                      <Select
                        style={{ maxWidth: 120 }}
                        options={NFTOptions}
                        placeholder="Standard"
                      >
                      </Select>
                    </Form.Item>
                    <div style={{ textAlign: 'right' }}>
                      <Button type="primary" loading={loading} htmlType="submit" >Transfer NFT</Button>
                    </div>
                  </Form>
                </Col>
              </Row>
            </>
          ) : null
        }
        {
          isConnected ? (
            <>
              <Descriptions
                title="Authenticate Identity Info"
                size="default"
                column={1}
              >
                <Descriptions.Item label="Principal ID">{principal}</Descriptions.Item>
                {/* <Descriptions.Item label="Identity">{activeProvider}</Descriptions.Item> */}

              </Descriptions>
              <Descriptions
                title="Authenticate Wallet Info"
                size="default"
                column={1}
              >
                <Descriptions.Item label="Principal">
                  {walletProvider?.wallets[0].principal}
                </Descriptions.Item>
                <Descriptions.Item label="AccountId">
                  {walletProvider?.wallets[0].accountId}
                </Descriptions.Item>
              </Descriptions>
            </>


          ) : null
        }
      </Space>
    </div>
  )
}

console.log('agent', navigator.userAgent)
const client = createClient({
  // providers: defaultProviders,
  providers: [
    (window as any).icx ? new ICX({
      // providerUrl: "https://ccmhe-vqaaa-aaaai-acmoq-cai.raw.ic0.app/",
      // providerUrl: "http://localhost:8080/",
    }) :
      new AstroX({
        // providerUrl: "https://ccmhe-vqaaa-aaaai-acmoq-cai.raw.ic0.app/",
        providerUrl: "http://localhost:8080/",
        delegationModes: ["global"],
      }),
    //  new PlugWallet(),
    //  new InternetIdentity()

  ],
  globalProviderConfig: {
    // host: 'http://localhost:3000',
    // dev: import.meta.env.DEV,
    dev: true,
    // ledgerCanisterId: "ryjl3-tyaaa-aaaaa-aaaba-cai",
    // ledgerHost: "http://localhost:8000",
    // whitelist: ["ryjl3-tyaaa-aaaaa-aaaba-cai"],
    // delegationModes:['global'],
    whitelist: ['qhbym-qaaaa-aaaaa-aaafq-cai'],
  },
})

export default () => (
  <Connect2ICProvider client={client}>
    <App />
  </Connect2ICProvider>
)
